"use client";

import { api } from "@/lib/api";
import type { BodyFieldMapping, Field, FieldOption, Flow, FlowToken, IntegrationTestResult, ResponseFieldMapping, Step, StepApiConfig, User } from "@/lib/types";
import { ArrowDown, ArrowUp, ChevronDown, ChevronUp, Copy, Eye, EyeOff, PencilLine, Plus, Save, Send, Shield, Trash2, Workflow } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import type { ReactNode } from "react";
import type { DragEvent } from "react";

const stepTypeOptions = [
  { value: 0, label: "Leitor / camera" },
  { value: 1, label: "Direcionamento para usuario" },
  { value: 2, label: "Acompanhamento externo" },
  { value: 3, label: "Automatica (start)" },
  { value: 4, label: "API envio" },
  { value: 5, label: "API consulta" }
];

const fieldTypeOptions = [
  { value: 0, label: "Texto" },
  { value: 1, label: "Numero" },
  { value: 2, label: "Data" },
  { value: 3, label: "Anexo" },
  { value: 4, label: "E-mail" },
  { value: 5, label: "Lista" },
  { value: 6, label: "Sim / Nao" },
  { value: 7, label: "Foto" },
  { value: 8, label: "Radio" }
];

const listFieldTypeOptions = fieldTypeOptions.filter(option => option.value !== 5);

const maskOptions = [
  { value: "", label: "Sem mascara" },
  { value: "cep", label: "CEP" },
  { value: "cpf", label: "CPF" },
  { value: "cnpj", label: "CNPJ" },
  { value: "telefone", label: "Telefone" },
  { value: "celular", label: "Celular" },
  { value: "valor", label: "Valor monetario" },
  { value: "data", label: "Data" },
  { value: "email", label: "E-mail" }
];

const intervalPresets = [
  { label: "5 minutos", value: "5 minutos" },
  { label: "15 minutos", value: "15 minutos" },
  { label: "30 minutos", value: "30 minutos" },
  { label: "1 hora", value: "60 minutos" },
  { label: "1 dia", value: "1440 minutos" },
  { label: "1 semana", value: "10080 minutos" }
];

const cronPresets = [
  { label: "Todo dia 08:00", value: "0 8 * * *" },
  { label: "1x por hora", value: "0 * * * *" },
  { label: "1x por semana", value: "0 8 * * 1" },
  { label: "1x por mes", value: "0 8 1 * *" },
  { label: "A cada 30 min", value: "*/30 * * * *" },
  { label: "Todo dia 12:00", value: "0 12 * * *" },
  { label: "Todo dia 18:00", value: "0 18 * * *" }
];

const weekdayOptions = [
  { value: "0", label: "Domingo" },
  { value: "1", label: "Segunda" },
  { value: "2", label: "Terca" },
  { value: "3", label: "Quarta" },
  { value: "4", label: "Quinta" },
  { value: "5", label: "Sexta" },
  { value: "6", label: "Sabado" }
];

function slugify(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .toLowerCase();
}

function buildAutoFieldKey(previousLabel: string, currentKey: string, nextLabel: string) {
  const previousAutoKey = slugify(previousLabel);
  const nextAutoKey = slugify(nextLabel);
  const isAutoGenerated = !currentKey || currentKey === previousAutoKey;

  return isAutoGenerated ? nextAutoKey : currentKey;
}

function createOption(parentFieldType?: number): FieldOption {
  if (parentFieldType === 5) {
    return { label: "", value: "", key: "", type: null, mask: "", required: false, order: 1 };
  }

  return { label: "", value: "", order: 1 };
}

function createField(): Field {
  return { label: "", key: "", type: 0, mask: "", required: false, order: 1, options: [] };
}

function createApiConfig(): StepApiConfig {
  return { validateTls: true, method: "GET", scheduleMode: "manual", sendFieldKeys: [], responseMappings: [], bodyMappings: [] };
}

function createStep(name = ""): Step {
  return {
    name,
    description: "",
    type: 1,
    order: 1,
    assignedUserIds: [],
    fields: [],
    apiConfig: createApiConfig()
  };
}

function createToken(): FlowToken {
  return { name: "", value: "", type: 0, headerName: "", active: true };
}

function createBodyMapping(): BodyFieldMapping {
  return { targetKey: "", sourceReference: "" };
}

function normalizeBodyTargetKey(value: string) {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^\w.]+/g, "_")
    .replace(/_+/g, "_")
    .replace(/(^[_.]+|[_.]+$)/g, "")
    .toLowerCase();
}

function typeNeedsApi(stepType: number) {
  return stepType === 2 || stepType === 4 || stepType === 5;
}

function fieldSupportsOptions(fieldType: number) {
  return fieldType === 5 || fieldType === 8;
}

function fieldSupportsMask(fieldType: number) {
  return fieldType !== 5 && fieldType !== 6 && fieldType !== 8 && fieldType !== 3 && fieldType !== 7;
}

function scheduleHelperText(scheduleMode?: string, scheduleValue?: string, helperText?: string | null, stepType?: number) {
  if (helperText) {
    return helperText;
  }

  if (scheduleMode === "interval" && scheduleValue) {
    return stepType === 3
      ? `Novas execucoes do fluxo serao iniciadas em intervalo de ${scheduleValue}.`
      : `A consulta tentara executar em intervalo de ${scheduleValue}.`;
  }

  if (scheduleMode === "cron" && scheduleValue) {
    return stepType === 3
      ? `Novas execucoes do fluxo seguirao a agenda cron ${scheduleValue}.`
      : `Expressao cron configurada: ${scheduleValue}.`;
  }

  return stepType === 3
    ? "Defina quando o fluxo deve iniciar automaticamente."
    : "Use os atalhos abaixo para preencher mais rapido e reduzir erros.";
}

function parseIntervalScheduleValue(value?: string) {
  const match = value?.match(/^(\d+)\s+minutos$/i);
  const totalMinutes = match ? Number(match[1]) : 60;

  if (totalMinutes % 1440 === 0) {
    return { amount: String(totalMinutes / 1440), unit: "days" as const };
  }

  if (totalMinutes % 60 === 0) {
    return { amount: String(totalMinutes / 60), unit: "hours" as const };
  }

  return { amount: String(totalMinutes), unit: "minutes" as const };
}

function buildIntervalScheduleValue(amount: string, unit: "minutes" | "hours" | "days") {
  const numericAmount = Math.max(1, Number(amount) || 1);
  const totalMinutes = unit === "days"
    ? numericAmount * 1440
    : unit === "hours"
      ? numericAmount * 60
      : numericAmount;

  return `${totalMinutes} minutos`;
}

function parseCronScheduleValue(value?: string) {
  const raw = (value ?? "").trim();

  const daily = raw.match(/^(\d{1,2})\s+(\d{1,2})\s+\*\s+\*\s+\*$/);
  if (daily) {
    return {
      recurrence: "daily" as const,
      time: `${daily[2].padStart(2, "0")}:${daily[1].padStart(2, "0")}`,
      weekday: "1",
      dayOfMonth: "1",
      raw
    };
  }

  const weekly = raw.match(/^(\d{1,2})\s+(\d{1,2})\s+\*\s+\*\s+([0-6])$/);
  if (weekly) {
    return {
      recurrence: "weekly" as const,
      time: `${weekly[2].padStart(2, "0")}:${weekly[1].padStart(2, "0")}`,
      weekday: weekly[3],
      dayOfMonth: "1",
      raw
    };
  }

  const monthly = raw.match(/^(\d{1,2})\s+(\d{1,2})\s+(\d{1,2})\s+\*\s+\*$/);
  if (monthly) {
    return {
      recurrence: "monthly" as const,
      time: `${monthly[2].padStart(2, "0")}:${monthly[1].padStart(2, "0")}`,
      weekday: "1",
      dayOfMonth: monthly[3],
      raw
    };
  }

  return {
    recurrence: "custom" as const,
    time: "08:00",
    weekday: "1",
    dayOfMonth: "1",
    raw
  };
}

function buildCronScheduleValue(
  recurrence: "daily" | "weekly" | "monthly" | "custom",
  time: string,
  weekday: string,
  dayOfMonth: string,
  raw: string
) {
  if (recurrence === "custom") {
    return raw;
  }

  const [hoursValue = "8", minutesValue = "0"] = (time || "08:00").split(":");
  const minutes = String(Math.min(59, Math.max(0, Number(minutesValue) || 0)));
  const hours = String(Math.min(23, Math.max(0, Number(hoursValue) || 0)));

  if (recurrence === "weekly") {
    return `${minutes} ${hours} * * ${weekday || "1"}`;
  }

  if (recurrence === "monthly") {
    const safeDay = String(Math.min(31, Math.max(1, Number(dayOfMonth) || 1)));
    return `${minutes} ${hours} ${safeDay} * *`;
  }

  return `${minutes} ${hours} * * *`;
}

function ScheduleEditor({
  config,
  onChange,
  isDraft,
  stepType
}: {
  config?: StepApiConfig | null;
  onChange: (patch: Partial<StepApiConfig>) => void;
  isDraft: boolean;
  stepType: number;
}) {
  const scheduleMode = config?.scheduleMode ?? "manual";
  const scheduleValue = config?.scheduleValue ?? "";
  const intervalState = parseIntervalScheduleValue(scheduleValue);
  const cronState = parseCronScheduleValue(scheduleValue);
  const helper = scheduleHelperText(scheduleMode, scheduleValue, config?.scheduleAssist?.helperText, stepType);

  function updateInterval(amount: string, unit: "minutes" | "hours" | "days") {
    onChange({ scheduleValue: buildIntervalScheduleValue(amount, unit) });
  }

  function updateCron(
    recurrence: "daily" | "weekly" | "monthly" | "custom",
    time: string,
    weekday: string,
    dayOfMonth: string,
    raw: string
  ) {
    onChange({ scheduleValue: buildCronScheduleValue(recurrence, time, weekday, dayOfMonth, raw) });
  }

  return (
    <div className="schedule-editor">
      <div className="field">
        <label>Agendamento</label>
        <select className="select" value={scheduleMode} onChange={e => onChange({ scheduleMode: e.target.value, scheduleValue: e.target.value === "manual" ? "" : scheduleValue })} disabled={!isDraft}>
          <option value="manual">Manual</option>
          <option value="interval">Intervalo</option>
          <option value="cron">Cron</option>
        </select>
      </div>

      {scheduleMode !== "manual" && (
        <div className="schedule-guide span2">
          <div className={`schedule-guide-card ${scheduleMode === "interval" ? "active" : ""}`}>
            <strong>Intervalo</strong>
            <p>Repete de tempos em tempos. Exemplo: a cada 15 minutos, 2 horas ou 1 dia.</p>
          </div>
          <div className={`schedule-guide-card ${scheduleMode === "cron" ? "active" : ""}`}>
            <strong>Cron</strong>
            <p>Agenda recorrente com horario fixo. Exemplo: todo dia 12:00 ou toda segunda 08:30.</p>
          </div>
        </div>
      )}

      {scheduleMode === "interval" && (
        <>
          <div className="field">
            <label>A cada</label>
            <input className="input" type="number" min={1} value={intervalState.amount} onChange={e => updateInterval(e.target.value, intervalState.unit)} disabled={!isDraft} />
          </div>
          <div className="field">
            <label>Unidade</label>
            <select className="select" value={intervalState.unit} onChange={e => updateInterval(intervalState.amount, e.target.value as "minutes" | "hours" | "days")} disabled={!isDraft}>
              <option value="minutes">Minutos</option>
              <option value="hours">Horas</option>
              <option value="days">Dias</option>
            </select>
          </div>
          <div className="field span2">
            <label>Atalhos</label>
            <div className="schedule-chip-row">
              {intervalPresets.map(preset => (
                <button key={preset.value} className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => onChange({ scheduleValue: preset.value })}>
                  {preset.label}
                </button>
              ))}
            </div>
          </div>
        </>
      )}

      {scheduleMode === "cron" && (
        <>
          <div className="field span2">
            <label>Recorrencia</label>
            <div className="schedule-chip-row">
              <button className={`btn ${cronState.recurrence === "daily" ? "btn-primary" : "btn-ghost"}`} type="button" disabled={!isDraft} onClick={() => updateCron("daily", cronState.time, cronState.weekday, cronState.dayOfMonth, cronState.raw)}>
                Diario
              </button>
              <button className={`btn ${cronState.recurrence === "weekly" ? "btn-primary" : "btn-ghost"}`} type="button" disabled={!isDraft} onClick={() => updateCron("weekly", cronState.time, cronState.weekday, cronState.dayOfMonth, cronState.raw)}>
                Semanal
              </button>
              <button className={`btn ${cronState.recurrence === "monthly" ? "btn-primary" : "btn-ghost"}`} type="button" disabled={!isDraft} onClick={() => updateCron("monthly", cronState.time, cronState.weekday, cronState.dayOfMonth, cronState.raw)}>
                Mensal
              </button>
              <button className={`btn ${cronState.recurrence === "custom" ? "btn-primary" : "btn-ghost"}`} type="button" disabled={!isDraft} onClick={() => onChange({ scheduleValue: cronState.raw || "0 8 * * *" })}>
                Avancado
              </button>
            </div>
            <div className="section-copy" style={{ marginTop: 8 }}>
              Agendamento unico por data/hora ainda nao existe no motor atual. Para testes, use recorrencias como diario, semanal ou mensal.
            </div>
          </div>

          {cronState.recurrence !== "custom" && (
            <>
              <div className="field">
                <label>Horario</label>
                <input className="input" type="time" value={cronState.time} onChange={e => updateCron(cronState.recurrence, e.target.value, cronState.weekday, cronState.dayOfMonth, cronState.raw)} disabled={!isDraft} />
              </div>

              {cronState.recurrence === "weekly" && (
                <div className="field">
                  <label>Dia da semana</label>
                  <select className="select" value={cronState.weekday} onChange={e => updateCron("weekly", cronState.time, e.target.value, cronState.dayOfMonth, cronState.raw)} disabled={!isDraft}>
                    {weekdayOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}
                  </select>
                </div>
              )}

              {cronState.recurrence === "monthly" && (
                <div className="field">
                  <label>Dia do mes</label>
                  <input className="input" type="number" min={1} max={31} value={cronState.dayOfMonth} onChange={e => updateCron("monthly", cronState.time, cronState.weekday, e.target.value, cronState.raw)} disabled={!isDraft} />
                </div>
              )}
            </>
          )}

          {cronState.recurrence === "custom" && (
            <div className="field span2">
              <label>Expressao cron</label>
              <input className="input" placeholder="Ex.: 0 8 * * *" value={cronState.raw} onChange={e => onChange({ scheduleValue: e.target.value })} disabled={!isDraft} />
            </div>
          )}

          <div className="field span2">
            <label>Atalhos de preenchimento</label>
            <div className="schedule-chip-row">
              {cronPresets.map(preset => (
                <button key={preset.value} className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => onChange({ scheduleValue: preset.value })}>
                  {preset.label}
                </button>
              ))}
            </div>
          </div>
        </>
      )}

      {scheduleMode !== "manual" && (
        <div className="field span2">
          <label>Resumo tecnico</label>
          <input className="input" value={scheduleValue} onChange={e => onChange({ scheduleValue: e.target.value })} disabled={!isDraft} />
          <div className="section-copy" style={{ marginTop: 8 }}>{helper}</div>
        </div>
      )}
    </div>
  );
}

type IntegrationFieldReference = {
  key: string;
  label: string;
  stepIndex: number;
  stepName: string;
  variable: string;
};

type BuilderSectionKey =
  | "flowUsers"
  | "stepBasics"
  | "fields"
  | "autoSchedule"
  | "integration"
  | "integrationFields"
  | "bodyMapping"
  | "responseMapping"
  | "test";

type BuilderSectionState = Record<BuilderSectionKey, boolean>;

function AccordionSection({
  title,
  description,
  open,
  onToggle,
  actions,
  soft = false,
  children
}: {
  title: string;
  description?: string;
  open: boolean;
  onToggle: () => void;
  actions?: ReactNode;
  soft?: boolean;
  children: ReactNode;
}) {
  return (
    <section className={`accordion-section${open ? " open" : ""}${soft ? " soft" : ""}`}>
      <div className="accordion-header">
        <button className="accordion-trigger" type="button" onClick={onToggle} aria-expanded={open}>
          <div>
            <h4>{title}</h4>
            {description && <p className="section-copy">{description}</p>}
          </div>
          <span className="accordion-icon">{open ? <ChevronUp size={18} /> : <ChevronDown size={18} />}</span>
        </button>
        {actions && <div className="accordion-actions">{actions}</div>}
      </div>
      {open && <div className="accordion-content">{children}</div>}
    </section>
  );
}

export function FlowBuilder({ flowId }: { flowId?: string }) {
  const router = useRouter();
  const [builderView, setBuilderView] = useState<"list" | "diagram">("list");
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [active, setActive] = useState(true);
  const [tokens, setTokens] = useState<FlowToken[]>([]);
  const [assignedUserIds, setAssignedUserIds] = useState<string[]>([]);
  const [users, setUsers] = useState<User[]>([]);
  const [flowUserFilter, setFlowUserFilter] = useState("");
  const [stepUserFilter, setStepUserFilter] = useState("");
  const [steps, setSteps] = useState<Step[]>([
    { ...createStep("Entrada do caminhao"), type: 0 },
    { ...createStep("Saida"), type: 1 }
  ]);
  const [editingStep, setEditingStep] = useState(0);
  const [loading, setLoading] = useState(!!flowId);
  const [saving, setSaving] = useState(false);
  const [creatingDraft, setCreatingDraft] = useState(false);
  const [publishing, setPublishing] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [visibleTokens, setVisibleTokens] = useState<Record<number, boolean>>({});
  const [flowStatus, setFlowStatus] = useState("Draft");
  const [flowVersion, setFlowVersion] = useState(1);
  const [testPayload, setTestPayload] = useState('{\n  "chaveAcesso": "12345678901234567890123456789012345678901234"\n}');
  const [testingStepId, setTestingStepId] = useState<string>("");
  const [testResult, setTestResult] = useState<IntegrationTestResult | null>(null);
  const [copiedReference, setCopiedReference] = useState("");
  const [dragStepIndex, setDragStepIndex] = useState<number | null>(null);
  const [dropStepIndex, setDropStepIndex] = useState<number | null>(null);
  const [openSections, setOpenSections] = useState<BuilderSectionState>({
    flowUsers: true,
    stepBasics: true,
    fields: true,
    autoSchedule: true,
    integration: true,
    integrationFields: false,
    bodyMapping: false,
    responseMapping: true,
    test: false
  });

  function applyLoadedFlow(flow: Flow) {
    setName(flow.name);
    setDescription(flow.description);
    setActive(flow.active);
    setTokens(flow.tokens);
    setAssignedUserIds(flow.assignedUserIds ?? []);
    setSteps(flow.steps.length > 0 ? flow.steps : [createStep()]);
    setEditingStep(0);
    setFlowStatus(flow.lifecycleStatus);
    setFlowVersion(flow.versionNumber);
  }

  async function reloadFlowState(successMessage: string) {
    if (!flowId) {
      setSuccess(successMessage);
      return;
    }

    try {
      applyLoadedFlow(await api<Flow>(`/flows/${flowId}`));
      setSuccess(successMessage);
    } catch (e) {
      const message = e instanceof Error ? e.message : "Nao foi possivel recarregar o fluxo.";
      setSuccess(`${successMessage} O fluxo foi salvo, mas houve falha ao recarregar a tela.`);
      setError(message);
    }
  }

  useEffect(() => {
    let activeRequest = true;

    api<User[]>("/users")
      .then(result => {
        if (activeRequest) {
          setUsers(result.filter(user => user.active !== false));
        }
      })
      .catch(() => {
        if (activeRequest) {
          setUsers([]);
        }
      });

    return () => {
      activeRequest = false;
    };
  }, []);

  useEffect(() => {
    if (!flowId) {
      return;
    }

    let activeRequest = true;
    setLoading(true);

    api<Flow>(`/flows/${flowId}`)
      .then(flow => {
        if (!activeRequest) {
          return;
        }
        applyLoadedFlow(flow);
      })
      .catch(e => {
        if (activeRequest) {
          setError(e instanceof Error ? e.message : "Nao foi possivel carregar o fluxo.");
        }
      })
      .finally(() => {
        if (activeRequest) {
          setLoading(false);
        }
      });

    return () => {
      activeRequest = false;
    };
  }, [flowId]);

  const isDraft = !flowId || flowStatus === "Draft";
  const currentStep = steps[editingStep];
  const toggleSection = (section: BuilderSectionKey) => {
    setOpenSections(current => ({ ...current, [section]: !current[section] }));
  };
  const availableIntegrationFields: IntegrationFieldReference[] = steps
    .slice(0, editingStep + 1)
    .flatMap((step, stepIndex) =>
      step.fields
        .filter(field => field.key.trim())
        .map(field => ({
          key: field.key.trim(),
          label: field.label.trim() || field.key.trim(),
          stepIndex,
          stepName: step.name.trim() || `Etapa ${stepIndex + 1}`,
          variable: `{{${field.key.trim()}}}`
        })));
  const selectedSendFieldKeys = currentStep?.apiConfig?.sendFieldKeys ?? [];
  const selectedSendFields = currentStep?.type === 4 && selectedSendFieldKeys.length > 0
    ? availableIntegrationFields.filter(field => selectedSendFieldKeys.includes(field.key))
    : availableIntegrationFields;
  const payloadPreview = selectedSendFields.length > 0
    ? `{\n${selectedSendFields.map(field => `  "${field.key}": "${field.variable}"`).join(",\n")}\n}`
    : "";
  const currentStepResponseMappings = currentStep?.apiConfig?.responseMappings ?? [];
  const currentBodyMappings = currentStep?.apiConfig?.bodyMappings ?? [];
  const orderedSelectedSendFields = selectedSendFieldKeys.length > 0
    ? selectedSendFieldKeys
      .map(key => availableIntegrationFields.find(field => field.key === key))
      .filter((field): field is IntegrationFieldReference => !!field)
    : availableIntegrationFields;
  const customBodyPreview = currentBodyMappings.length > 0
    ? `{\n${currentBodyMappings
      .filter(mapping => mapping.targetKey.trim() || mapping.sourceReference.trim())
      .map(mapping => `  "${mapping.targetKey || "campo"}": "${mapping.sourceReference || "{{variavel}}"}`).join(",\n")}\n}`
    : "";
  const filteredFlowUsers = users.filter(user => user.name.toLowerCase().includes(flowUserFilter.toLowerCase()) || user.email.toLowerCase().includes(flowUserFilter.toLowerCase()));
  const filteredStepUsers = users.filter(user => user.name.toLowerCase().includes(stepUserFilter.toLowerCase()) || user.email.toLowerCase().includes(stepUserFilter.toLowerCase()));

  function updateStep(index: number, patch: Partial<Step>) {
    setSteps(current => current.map((step, stepIndex) => stepIndex === index ? { ...step, ...patch } : step));
  }

  function updateField(stepIndex: number, fieldIndex: number, patch: Partial<Field>) {
    setSteps(current => current.map((step, currentStepIndex) => {
      if (currentStepIndex !== stepIndex) {
        return step;
      }

      return {
        ...step,
        fields: step.fields.map((field, currentFieldIndex) => currentFieldIndex === fieldIndex ? { ...field, ...patch } : field)
      };
    }));
  }

  function updateOption(stepIndex: number, fieldIndex: number, optionIndex: number, patch: Partial<FieldOption>) {
    setSteps(current => current.map((step, currentStepIndex) => {
      if (currentStepIndex !== stepIndex) {
        return step;
      }

      return {
        ...step,
        fields: step.fields.map((field, currentFieldIndex) => {
          if (currentFieldIndex !== fieldIndex) {
            return field;
          }

          return {
            ...field,
            options: field.options.map((option, currentOptionIndex) => currentOptionIndex === optionIndex ? { ...option, ...patch } : option)
          };
        })
      };
    }));
  }

  function updateToken(index: number, patch: Partial<FlowToken>) {
    setTokens(current => current.map((token, tokenIndex) => tokenIndex === index ? { ...token, ...patch } : token));
  }

  function updateApiConfig(stepIndex: number, patch: Partial<StepApiConfig>) {
    setSteps(current => current.map((step, currentStepIndex) => currentStepIndex === stepIndex
      ? { ...step, apiConfig: { ...createApiConfig(), ...step.apiConfig, ...patch } }
      : step));
  }

  function toggleFlowUser(userId: string) {
    setAssignedUserIds(current => current.includes(userId)
      ? current.filter(id => id !== userId)
      : [...current, userId]);
  }

  function toggleStepUser(userId: string) {
    const currentUserIds = currentStep?.assignedUserIds ?? [];
    updateStep(editingStep, {
      assignedUserIds: currentUserIds.includes(userId)
        ? currentUserIds.filter(id => id !== userId)
        : [...currentUserIds, userId]
    });
  }

  async function copyReference(reference: string) {
    try {
      await navigator.clipboard.writeText(reference);
      setCopiedReference(reference);
      window.setTimeout(() => setCopiedReference(current => current === reference ? "" : current), 1800);
    } catch {
      setCopiedReference("");
    }
  }

  function insertIntoApiConfig(fieldName: "url" | "queryTemplate", reference: string) {
    const currentValue = currentStep?.apiConfig?.[fieldName] ?? "";
    updateApiConfig(editingStep, { [fieldName]: `${currentValue}${reference}` });
  }

  function toggleSendFieldKey(fieldKey: string) {
    const currentKeys = currentStep?.apiConfig?.sendFieldKeys ?? [];
    const nextKeys = currentKeys.includes(fieldKey)
      ? currentKeys.filter(key => key !== fieldKey)
      : [...currentKeys, fieldKey];

    updateApiConfig(editingStep, { sendFieldKeys: nextKeys });
  }

  function selectAllSendFields() {
    updateApiConfig(editingStep, { sendFieldKeys: availableIntegrationFields.map(field => field.key) });
  }

  function clearSendFields() {
    updateApiConfig(editingStep, { sendFieldKeys: [] });
  }

  function moveSendField(fieldKey: string, direction: "up" | "down") {
    const currentKeys = currentStep?.apiConfig?.sendFieldKeys ?? [];
    if (currentKeys.length < 2) {
      return;
    }

    const index = currentKeys.indexOf(fieldKey);
    if (index < 0) {
      return;
    }

    const nextIndex = direction === "up" ? index - 1 : index + 1;
    if (nextIndex < 0 || nextIndex >= currentKeys.length) {
      return;
    }

    const reordered = [...currentKeys];
    [reordered[index], reordered[nextIndex]] = [reordered[nextIndex], reordered[index]];
    updateApiConfig(editingStep, { sendFieldKeys: reordered });
  }

  function insertReferenceIntoTestPayload(reference: IntegrationFieldReference) {
    let parsed: Record<string, string>;

    try {
      parsed = JSON.parse(testPayload);
    } catch {
      parsed = {};
    }

    parsed[reference.key] = reference.variable;
    setTestPayload(JSON.stringify(parsed, null, 2));
  }

  function updateResponseMapping(fieldKey: string, responsePath: string) {
    const nextMappings = (currentStep?.apiConfig?.responseMappings ?? []).filter(mapping => mapping.fieldKey !== fieldKey);

    if (responsePath.trim()) {
      nextMappings.push({ fieldKey, responsePath: responsePath.trim() });
    }

    updateApiConfig(editingStep, { responseMappings: nextMappings });
  }

  function getResponseMappingValue(fieldKey: string) {
    return currentStepResponseMappings.find(mapping => mapping.fieldKey === fieldKey)?.responsePath ?? "";
  }

  function fillResponseMappingsByFieldKey() {
    const nextMappings: ResponseFieldMapping[] = currentStep.fields
      .filter(field => field.key.trim())
      .map(field => ({ fieldKey: field.key.trim(), responsePath: field.key.trim() }));

    updateApiConfig(editingStep, { responseMappings: nextMappings });
  }

  function updateBodyMapping(index: number, patch: Partial<BodyFieldMapping>) {
    const nextMappings = currentBodyMappings.map((mapping, mappingIndex) => mappingIndex === index ? { ...mapping, ...patch } : mapping);
    updateApiConfig(editingStep, { bodyMappings: nextMappings });
  }

  function addBodyMapping() {
    updateApiConfig(editingStep, { bodyMappings: [...currentBodyMappings, createBodyMapping()] });
  }

  function removeBodyMapping(index: number) {
    updateApiConfig(editingStep, { bodyMappings: currentBodyMappings.filter((_, mappingIndex) => mappingIndex !== index) });
  }

  function duplicateBodyMapping(index: number) {
    const mapping = currentBodyMappings[index];
    if (!mapping) {
      return;
    }

    const duplicated = [...currentBodyMappings];
    duplicated.splice(index + 1, 0, { ...mapping });
    updateApiConfig(editingStep, { bodyMappings: duplicated });
  }

  function moveBodyMapping(index: number, direction: "up" | "down") {
    const nextIndex = direction === "up" ? index - 1 : index + 1;
    if (nextIndex < 0 || nextIndex >= currentBodyMappings.length) {
      return;
    }

    const reordered = [...currentBodyMappings];
    [reordered[index], reordered[nextIndex]] = [reordered[nextIndex], reordered[index]];
    updateApiConfig(editingStep, { bodyMappings: reordered });
  }

  function buildBodyMappingsFromSelectedFields() {
    const sourceFields = orderedSelectedSendFields.length > 0 ? orderedSelectedSendFields : availableIntegrationFields;
    const nextMappings: BodyFieldMapping[] = sourceFields.map(field => ({
      targetKey: field.key,
      sourceReference: field.variable
    }));

    updateApiConfig(editingStep, { bodyMappings: nextMappings });
  }

  function addStep() {
    setSteps(current => [...current, createStep()]);
    setEditingStep(steps.length);
  }

  function reorderStep(fromIndex: number, toIndex: number) {
    setSteps(current => {
      if (fromIndex === toIndex || fromIndex < 0 || toIndex < 0 || fromIndex >= current.length || toIndex >= current.length) {
        return current;
      }

      const reordered = [...current];
      const [movedStep] = reordered.splice(fromIndex, 1);
      reordered.splice(toIndex, 0, movedStep);
      setEditingStep(toIndex);
      return reordered;
    });
  }

  function moveStep(index: number, direction: "left" | "right") {
    const nextIndex = direction === "left" ? index - 1 : index + 1;
    reorderStep(index, nextIndex);
  }

  function handleStepDragStart(index: number) {
    if (!isDraft) {
      return;
    }

    setDragStepIndex(index);
    setDropStepIndex(index);
  }

  function handleStepDragOver(event: DragEvent<HTMLElement>, index: number) {
    if (!isDraft || dragStepIndex === null) {
      return;
    }

    event.preventDefault();
    if (dropStepIndex !== index) {
      setDropStepIndex(index);
    }
  }

  function handleStepDrop(index: number) {
    if (!isDraft || dragStepIndex === null) {
      return;
    }

    reorderStep(dragStepIndex, index);
    setDragStepIndex(null);
    setDropStepIndex(null);
  }

  function handleStepDragEnd() {
    setDragStepIndex(null);
    setDropStepIndex(null);
  }

  function removeStep(index: number) {
    const next = steps.filter((_, stepIndex) => stepIndex !== index);
    setSteps(next.length > 0 ? next : [createStep()]);
    setEditingStep(Math.max(0, index - 1));
  }

  async function saveFlow() {
    if (flowId && !isDraft) {
      setError("Crie um rascunho antes de alterar uma versao publicada.");
      return;
    }

    setSaving(true);
    setError("");
    setSuccess("");

    const payload = {
      name,
      description,
      active,
      assignedUserIds,
      tokens: tokens.map(token => ({
        ...token,
        name: token.name.trim(),
        headerName: token.headerName?.trim(),
        value: token.value ?? ""
      })),
      steps: steps.map((step, stepIndex) => ({
        ...step,
        order: stepIndex + 1,
        fields: step.fields.map((field, fieldIndex) => ({
          ...field,
          order: fieldIndex + 1,
          key: field.key.trim(),
          label: field.label.trim(),
          options: field.options.map((option, optionIndex) => ({
            ...option,
            order: optionIndex + 1,
            label: option.label.trim(),
            value: option.value.trim(),
            key: field.type === 5 ? (option.key?.trim() || option.value.trim() || null) : (option.key?.trim() || null),
            type: field.type === 5 ? (option.type ?? 0) : (option.type ?? null),
            mask: option.mask?.trim() || null,
            required: option.required ?? false
          }))
        }))
      }))
    };

    try {
      if (flowId) {
        const result = await api<{ id: string }>(`/flows/${flowId}`, { method: "PUT", body: JSON.stringify(payload) });
        if (result.id && result.id !== flowId) {
          router.replace(`/fluxos/${result.id}`);
          return;
        }
        await reloadFlowState("Rascunho salvo com sucesso.");
      } else {
        const result = await api<{ id: string }>(`/flows`, { method: "POST", body: JSON.stringify(payload) });
        router.replace(`/fluxos/${result.id}`);
        return;
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "Nao foi possivel salvar o fluxo.");
    } finally {
      setSaving(false);
    }
  }

  async function createDraftFromPublished() {
    if (!flowId) {
      return;
    }

    setCreatingDraft(true);
    setError("");

    try {
      const result = await api<{ id: string }>(`/flows/${flowId}/draft`, { method: "POST" });
      router.replace(`/fluxos/${result.id}`);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Nao foi possivel criar o rascunho.");
    } finally {
      setCreatingDraft(false);
    }
  }

  async function publishDraft() {
    if (!flowId) {
      return;
    }

    setPublishing(true);
    setError("");
    setSuccess("");

    try {
      await api(`/flows/${flowId}/publish`, { method: "POST" });
      await reloadFlowState("Fluxo publicado com sucesso.");
    } catch (e) {
      setError(e instanceof Error ? e.message : "Nao foi possivel publicar o fluxo.");
    } finally {
      setPublishing(false);
    }
  }

  async function testIntegration() {
    if (!flowId || !currentStep?.id) {
      setError("Salve o rascunho da etapa antes de testar a integracao.");
      return;
    }

    let parsed: Record<string, unknown>;
    try {
      parsed = JSON.parse(testPayload);
    } catch {
      setError("O JSON de teste esta invalido.");
      return;
    }

    setTestingStepId(currentStep.id);
    setError("");
    setTestResult(null);

    try {
      const result = await api<IntegrationTestResult>(`/flows/${flowId}/steps/${currentStep.id}/test-integration`, {
        method: "POST",
        body: JSON.stringify({ data: parsed })
      });
      setTestResult(result);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Nao foi possivel testar a integracao.");
    } finally {
      setTestingStepId("");
    }
  }

  if (loading) {
    return <div className="empty">Carregando estrutura do fluxo...</div>;
  }

  return <>
    <div className="pagehead">
      <div>
        <span className="eyebrow">Construtor</span>
        <h1 className="title">{flowId ? "Editar fluxo" : "Criar novo fluxo"}</h1>
        <p className="subtitle">Cada etapa pode ter seus proprios campos, gatilhos e integracoes.</p>
      </div>
      {flowId && <span className={`badge ${isDraft ? "inprogress" : "completed"}`}>v{flowVersion} - {isDraft ? "Rascunho" : "Publicado"}</span>}
    </div>

    {error && <div className="error">{error}</div>}
    {success && <div className="notice">{success}</div>}
    {flowId && !isDraft && <div className="notice">Esta versao publicada esta protegida. Crie um rascunho para editar sem afetar as execucoes em andamento.</div>}

    <section className="card formcard">
      <h2 className="section-title">Informacoes basicas</h2>
      <p className="section-copy">Defina a identidade do fluxo e mantenha o cadastro ativo para a operacao.</p>
      <div className="formgrid">
        <div className="field">
          <label>Nome do fluxo *</label>
          <input className="input" value={name} onChange={e => setName(e.target.value)} disabled={!isDraft} />
        </div>
        <div className="field">
          <label>Status</label>
          <label className="toggle-line">
            <input type="checkbox" checked={active} onChange={e => setActive(e.target.checked)} disabled={!isDraft} />
            Fluxo ativo para novas entradas
          </label>
        </div>
        <div className="field span2">
          <label>Descricao</label>
          <textarea className="textarea" value={description} onChange={e => setDescription(e.target.value)} disabled={!isDraft} />
        </div>
      </div>

      <hr className="divider" />

      <div className="section-header">
        <div>
          <h2 className="section-title">Tokens do fluxo</h2>
          <p className="section-copy">Cadastre credenciais reutilizaveis para as integracoes das etapas.</p>
        </div>
        <button className="btn btn-secondary" type="button" disabled={!isDraft} onClick={() => setTokens(current => [...current, createToken()])}>
          <Shield size={16} />
          Adicionar token
        </button>
      </div>

      <div className="token-list">
        {tokens.length === 0 && <div className="empty compact">Nenhum token cadastrado neste fluxo.</div>}
        {tokens.map((token, index) =>
          <div className="token-card" key={`${token.id ?? "new"}-${index}`}>
            <div className="token-grid">
              <div className="field">
                <label>Nome</label>
                <input className="input" value={token.name} onChange={e => updateToken(index, { name: e.target.value })} disabled={!isDraft} />
              </div>
              <div className="field">
                <label>Tipo</label>
                <select className="select" value={token.type} onChange={e => updateToken(index, { type: Number(e.target.value) })} disabled={!isDraft}>
                  <option value={0}>Bearer</option>
                  <option value={1}>API key</option>
                </select>
              </div>
              <div className="field">
                <label>Header</label>
                <input className="input" placeholder="Authorization ou X-API-Key" value={token.headerName ?? ""} onChange={e => updateToken(index, { headerName: e.target.value })} disabled={!isDraft} />
              </div>
              <div className="field">
                <label>Valor</label>
                <div className="password-wrap">
                  <input className="input" type={visibleTokens[index] ? "text" : "password"} value={token.value ?? ""} onChange={e => updateToken(index, { value: e.target.value })} disabled={!isDraft} />
                  <button className="icon-btn" type="button" onClick={() => setVisibleTokens(current => ({ ...current, [index]: !current[index] }))}>
                    {visibleTokens[index] ? <EyeOff size={16} /> : <Eye size={16} />}
                  </button>
                </div>
              </div>
            </div>
            <div className="row-actions">
              <label className="toggle-line">
                <input type="checkbox" checked={token.active} onChange={e => updateToken(index, { active: e.target.checked })} disabled={!isDraft} />
                Token ativo
              </label>
              <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => setTokens(current => current.filter((_, tokenIndex) => tokenIndex !== index))}>
                <Trash2 size={16} />
                Remover
              </button>
            </div>
          </div>)}
      </div>

      <hr className="divider" />

      <div className="section-header">
        <div>
          <h2 className="section-title">Etapas sequenciais</h2>
          <p className="section-copy">Use o lapis para abrir os campos e a configuracao especifica de cada etapa.</p>
        </div>
        <div className="builder-toolbar">
          <div className="view-toggle" role="tablist" aria-label="Modo de visualizacao das etapas">
            <button
              className={`view-toggle-btn ${builderView === "list" ? "active" : ""}`}
              type="button"
              role="tab"
              aria-selected={builderView === "list"}
              onClick={() => setBuilderView("list")}
            >
              Visao 1
            </button>
            <button
              className={`view-toggle-btn ${builderView === "diagram" ? "active" : ""}`}
              type="button"
              role="tab"
              aria-selected={builderView === "diagram"}
              onClick={() => setBuilderView("diagram")}
            >
              Visao 2
            </button>
          </div>
          <button className="btn btn-secondary" type="button" disabled={!isDraft} onClick={addStep}>
            <Plus size={16} />
            Adicionar etapa
          </button>
        </div>
      </div>

      <div className={`step-board ${builderView === "diagram" ? "step-board-diagram" : ""}`}>
        {builderView === "list"
          ? <div className="step-list">
            {steps.map((step, index) =>
              <article
                className={`step-card ${editingStep === index ? "active" : ""} ${dragStepIndex === index ? "dragging" : ""} ${dropStepIndex === index ? "drop-target" : ""}`}
                key={`${step.id ?? "new"}-${index}`}
                draggable={isDraft}
                onDragStart={() => handleStepDragStart(index)}
                onDragOver={event => handleStepDragOver(event, index)}
                onDrop={() => handleStepDrop(index)}
                onDragEnd={handleStepDragEnd}
              >
                <div className="step-card-top">
                  <span className="step-chip">{index + 1}</span>
                  <div style={{ display: "flex", gap: 8 }}>
                    <button className="icon-btn" type="button" disabled={!isDraft || index === 0} onClick={() => moveStep(index, "left")} aria-label={`Mover etapa ${index + 1} para cima`}>
                      <ArrowUp size={16} />
                    </button>
                    <button className="icon-btn" type="button" disabled={!isDraft || index === steps.length - 1} onClick={() => moveStep(index, "right")} aria-label={`Mover etapa ${index + 1} para baixo`}>
                      <ArrowDown size={16} />
                    </button>
                    <button className="icon-btn" type="button" onClick={() => setEditingStep(index)}>
                      <PencilLine size={16} />
                    </button>
                  </div>
                </div>
                <strong>{step.name || `Etapa ${index + 1}`}</strong>
                <small>{stepTypeOptions.find(option => option.value === step.type)?.label}</small>
                <div className="step-meta">
                  <span>{step.fields.length} campo(s)</span>
                  {typeNeedsApi(step.type) && <span>Integracao</span>}
                </div>
                <button className="btn btn-ghost btn-inline" type="button" disabled={!isDraft} onClick={() => removeStep(index)}>
                  <Trash2 size={15} />
                  Excluir
                </button>
              </article>)}
          </div>
          : <div className="step-diagram card">
            <div className="step-diagram-header">
              <div>
                <h3 className="section-title">Mapa visual do fluxo</h3>
                <p className="section-copy">Clique em qualquer etapa para abrir a configuracao completa abaixo. Voce tambem pode arrastar para reorganizar.</p>
              </div>
            </div>
            <div className="step-diagram-scroll">
              <div className="step-diagram-canvas" role="list" aria-label="Etapas do fluxo em diagrama">
                {steps.map((step, index) =>
                  <div
                    className={`diagram-node ${editingStep === index ? "active" : ""} ${dragStepIndex === index ? "dragging" : ""} ${dropStepIndex === index ? "drop-target" : ""}`}
                    key={`${step.id ?? "new"}-${index}`}
                    role="listitem"
                    draggable={isDraft}
                    onDragStart={() => handleStepDragStart(index)}
                    onDragOver={event => handleStepDragOver(event, index)}
                    onDrop={() => handleStepDrop(index)}
                    onDragEnd={handleStepDragEnd}
                  >
                    <button className="diagram-node-card" type="button" onClick={() => setEditingStep(index)}>
                      <div className="diagram-node-top">
                        <span className="step-chip">{index + 1}</span>
                        <span className="diagram-node-kind">{typeNeedsApi(step.type) ? "Integrado" : "Manual"}</span>
                      </div>
                      <strong>{step.name || `Etapa ${index + 1}`}</strong>
                      <small>{stepTypeOptions.find(option => option.value === step.type)?.label}</small>
                      <div className="step-meta">
                        <span>{step.fields.length} campo(s)</span>
                        {typeNeedsApi(step.type) && <span>API</span>}
                      </div>
                    </button>
                    <div className="diagram-node-actions">
                      <button className="icon-btn" type="button" disabled={!isDraft || index === 0} onClick={() => moveStep(index, "left")} aria-label={`Mover etapa ${index + 1} para a esquerda`}>
                        <ArrowUp size={16} />
                      </button>
                      <button className="icon-btn" type="button" disabled={!isDraft || index === steps.length - 1} onClick={() => moveStep(index, "right")} aria-label={`Mover etapa ${index + 1} para a direita`}>
                        <ArrowDown size={16} />
                      </button>
                      <button className="icon-btn" type="button" onClick={() => setEditingStep(index)} aria-label={`Editar etapa ${index + 1}`}>
                        <PencilLine size={16} />
                      </button>
                      <button className="icon-btn" type="button" disabled={!isDraft} onClick={() => removeStep(index)} aria-label={`Excluir etapa ${index + 1}`}>
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </div>)}
              </div>
            </div>
          </div>}

        {currentStep && <div className="step-editor card">
          <div className="step-editor-header">
            <div>
              <span className="eyebrow">Etapa {editingStep + 1}</span>
              <h3>{currentStep.name || "Configuracao da etapa"}</h3>
            </div>
            <Workflow size={20} />
          </div>

          <AccordionSection
            title="Acesso ao fluxo"
            description="Quem estiver vinculado ao fluxo pode localizar e executar tarefas deste fluxo inteiro."
            open={openSections.flowUsers}
            onToggle={() => toggleSection("flowUsers")}
            soft
          >
            <div className="edit-panel" style={{ marginBottom: 0 }}>
              {users.length === 0 && <div className="empty compact">Nenhum usuario disponivel para vincular.</div>}

              {users.length > 0 && <>
                <input className="input" placeholder="Buscar usuario no fluxo..." value={flowUserFilter} onChange={e => setFlowUserFilter(e.target.value)} disabled={!isDraft} />
                <div style={{ marginTop: 12, maxHeight: 220, overflow: "auto", border: "1px solid var(--line)", borderRadius: 12, padding: 10, display: "grid", gap: 8 }}>
                  {filteredFlowUsers.map(user => <label key={user.id} className="toggle-line compact" style={{ padding: "9px 12px", border: "1px solid var(--line)", borderRadius: 10, background: assignedUserIds.includes(user.id) ? "#eef7f2" : "#fff" }}>
                    <input type="checkbox" checked={assignedUserIds.includes(user.id)} onChange={() => toggleFlowUser(user.id)} disabled={!isDraft} />
                    {user.name} <small style={{ color: "var(--muted)" }}>{user.email}</small>
                  </label>)}
                  {filteredFlowUsers.length === 0 && <div className="empty compact">Nenhum usuario encontrado.</div>}
                </div>
              </>}
            </div>
          </AccordionSection>

          <AccordionSection
            title="Cadastro da etapa"
            description="Defina nome, tipo, responsaveis e contexto geral desta etapa."
            open={openSections.stepBasics}
            onToggle={() => toggleSection("stepBasics")}
          >
            <div className="formgrid">
              <div className="field">
                <label>Nome da etapa *</label>
                <input className="input" value={currentStep.name} onChange={e => updateStep(editingStep, { name: e.target.value })} disabled={!isDraft} />
              </div>
              <div className="field">
                <label>Tipo de entrada</label>
                <select className="select" value={currentStep.type} onChange={e => updateStep(editingStep, { type: Number(e.target.value), apiConfig: createApiConfig() })} disabled={!isDraft}>
                  {stepTypeOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}
                </select>
              </div>
              <div className="field span2">
                <label>Usuarios da etapa</label>
                <input className="input" placeholder="Buscar usuario na etapa..." value={stepUserFilter} onChange={e => setStepUserFilter(e.target.value)} disabled={!isDraft} />
                <div style={{ maxHeight: 220, overflow: "auto", border: "1px solid var(--line)", borderRadius: 12, padding: 10, display: "grid", gap: 8 }}>
                  <label className="toggle-line compact" style={{ padding: "9px 12px", border: "1px solid var(--line)", borderRadius: 10, background: currentStep.assignedUserIds.length === 0 ? "#eef7f2" : "#fff" }}>
                    <input type="checkbox" checked={currentStep.assignedUserIds.length === 0} onChange={() => updateStep(editingStep, { assignedUserIds: [] })} disabled={!isDraft} />
                    Qualquer usuario com acesso ao fluxo
                  </label>
                  {filteredStepUsers.map(user => <label key={user.id} className="toggle-line compact" style={{ padding: "9px 12px", border: "1px solid var(--line)", borderRadius: 10, background: currentStep.assignedUserIds.includes(user.id) ? "#eef7f2" : "#fff" }}>
                    <input type="checkbox" checked={currentStep.assignedUserIds.includes(user.id)} onChange={() => toggleStepUser(user.id)} disabled={!isDraft} />
                    {user.name} <small style={{ color: "var(--muted)" }}>{user.email}</small>
                  </label>)}
                  {filteredStepUsers.length === 0 && <div className="empty compact">Nenhum usuario encontrado.</div>}
                </div>
              </div>
              <div className="field span2">
                <label>Descricao</label>
                <textarea className="textarea" value={currentStep.description ?? ""} onChange={e => updateStep(editingStep, { description: e.target.value })} disabled={!isDraft} />
              </div>
            </div>
          </AccordionSection>

          <AccordionSection
            title="Campos de registro"
            description="Esses campos aparecem quando a etapa precisa capturar dados."
            open={openSections.fields}
            onToggle={() => toggleSection("fields")}
            actions={<button className="btn btn-secondary" type="button" disabled={!isDraft} onClick={() => updateStep(editingStep, { fields: [...currentStep.fields, createField()] })}>
              <Plus size={16} />
              Adicionar campo
            </button>}
          >
            <div className="builder">
              {currentStep.fields.length === 0 && <div className="empty compact">Nenhum campo cadastrado nesta etapa.</div>}
              {currentStep.fields.map((field, fieldIndex) =>
                <div className="field-block" key={`${field.id ?? "new"}-${fieldIndex}`}>
                  <div className="builder-row builder-row-field">
                    <input
                      className="input"
                      placeholder="Rotulo"
                      value={field.label}
                      onChange={e => updateField(editingStep, fieldIndex, {
                        label: e.target.value,
                        key: buildAutoFieldKey(field.label, field.key, e.target.value)
                      })}
                      disabled={!isDraft}
                    />
                    <input className="input" placeholder="chave_do_campo" value={field.key} onChange={e => updateField(editingStep, fieldIndex, { key: slugify(e.target.value) })} disabled={!isDraft} />
                    <select className="select" value={field.type} onChange={e => updateField(editingStep, fieldIndex, {
                      type: Number(e.target.value),
                      mask: fieldSupportsMask(Number(e.target.value)) ? field.mask ?? "" : "",
                      options: fieldSupportsOptions(Number(e.target.value)) ? (field.options.length ? field.options : [createOption(Number(e.target.value))]) : []
                    })} disabled={!isDraft}>
                      {fieldTypeOptions.map(option => <option key={option.value} value={option.value}>{option.label}</option>)}
                    </select>
                    <select className="select" value={field.mask ?? ""} onChange={e => updateField(editingStep, fieldIndex, { mask: e.target.value || "" })} disabled={!isDraft || !fieldSupportsMask(field.type)}>
                      {maskOptions.map(option => <option key={option.value || "empty"} value={option.value}>{option.label}</option>)}
                    </select>
                    <label className="toggle-line compact">
                      <input type="checkbox" checked={field.required} onChange={e => updateField(editingStep, fieldIndex, { required: e.target.checked })} disabled={!isDraft} />
                      Obrigatorio
                    </label>
                    <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => updateStep(editingStep, { fields: currentStep.fields.filter((_, currentFieldIndex) => currentFieldIndex !== fieldIndex) })}>
                      <Trash2 size={16} />
                    </button>
                  </div>

                  {fieldSupportsOptions(field.type) && <div className="options-box">
                    <div className="section-header">
                    <div>
                        <h4>{field.type === 8 ? "Opcoes do radio" : "Campos da lista"}</h4>
                        <p className="section-copy">{field.type === 8 ? "Cadastre as opcoes exibidas como selecao unica em botoes." : "A lista pode usar os mesmos tipos do campo principal, exceto outra lista aninhada."}</p>
                      </div>
                      <button className="btn btn-secondary" type="button" disabled={!isDraft} onClick={() => updateField(editingStep, fieldIndex, { options: [...field.options, createOption(field.type)] })}>
                        <Plus size={14} />
                        {field.type === 8 ? "Nova opcao" : "Novo campo"}
                      </button>
                    </div>
                    {field.options.map((option, optionIndex) => field.type === 8
                      ? <div className="builder-row option-row" key={`${option.id ?? "new"}-${optionIndex}`}>
                        <input className="input" placeholder="Nome da opcao" value={option.label} onChange={e => updateOption(editingStep, fieldIndex, optionIndex, { label: e.target.value })} disabled={!isDraft} />
                        <input className="input" placeholder="Valor enviado" value={option.value} onChange={e => updateOption(editingStep, fieldIndex, optionIndex, { value: e.target.value })} disabled={!isDraft} />
                        <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => updateField(editingStep, fieldIndex, { options: field.options.filter((_, currentOptionIndex) => currentOptionIndex !== optionIndex) })}>
                          <Trash2 size={15} />
                        </button>
                      </div>
                      : <div className="builder-row builder-row-field" key={`${option.id ?? "new"}-${optionIndex}`}>
                        <input
                          className="input"
                          placeholder="Rotulo"
                          value={option.label}
                          onChange={e => updateOption(editingStep, fieldIndex, optionIndex, {
                            label: e.target.value,
                            key: buildAutoFieldKey(option.label, option.key ?? option.value ?? "", e.target.value),
                            value: buildAutoFieldKey(option.label, option.key ?? option.value ?? "", e.target.value)
                          })}
                          disabled={!isDraft}
                        />
                        <input className="input" placeholder="chave_do_campo" value={option.key ?? option.value ?? ""} onChange={e => updateOption(editingStep, fieldIndex, optionIndex, { key: slugify(e.target.value), value: slugify(e.target.value) })} disabled={!isDraft} />
                        <select className="select" value={option.type ?? ""} onChange={e => updateOption(editingStep, fieldIndex, optionIndex, {
                          type: e.target.value ? Number(e.target.value) : null,
                          mask: e.target.value && fieldSupportsMask(Number(e.target.value)) ? option.mask ?? "" : ""
                        })} disabled={!isDraft}>
                          <option value="">Tipo</option>
                          {listFieldTypeOptions.map(typeOption => <option key={typeOption.value} value={typeOption.value}>{typeOption.label}</option>)}
                        </select>
                        <select className="select" value={option.mask ?? ""} onChange={e => updateOption(editingStep, fieldIndex, optionIndex, { mask: e.target.value || "" })} disabled={!isDraft || !fieldSupportsMask(option.type ?? -1)}>
                          {maskOptions.map(maskOption => <option key={maskOption.value || "empty"} value={maskOption.value}>{maskOption.label}</option>)}
                        </select>
                        <label className="toggle-line compact">
                          <input type="checkbox" checked={option.required ?? false} onChange={e => updateOption(editingStep, fieldIndex, optionIndex, { required: e.target.checked })} disabled={!isDraft} />
                          Obrigatorio
                        </label>
                        <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => updateField(editingStep, fieldIndex, { options: field.options.filter((_, currentOptionIndex) => currentOptionIndex !== optionIndex) })}>
                          <Trash2 size={15} />
                        </button>
                      </div>)}
                  </div>}
                </div>)}
            </div>
          </AccordionSection>

          {currentStep.type === 3 && <AccordionSection
            title="Agendamento de inicio"
            description="Configure quando novas execucoes deste fluxo devem ser iniciadas automaticamente."
            open={openSections.autoSchedule}
            onToggle={() => toggleSection("autoSchedule")}
          >
            <div className="formgrid">
              <ScheduleEditor config={currentStep.apiConfig} onChange={patch => updateApiConfig(editingStep, patch)} isDraft={isDraft} stepType={currentStep.type} />
            </div>
          </AccordionSection>}

          {typeNeedsApi(currentStep.type) && <AccordionSection
            title="Integracao da etapa"
            description="Configure envio, consulta ou monitoramento por API na propria etapa."
            open={openSections.integration}
            onToggle={() => toggleSection("integration")}
          >
            <div className="formgrid">
              <div className="field">
                <label>URL</label>
                <input className="input" placeholder="https://api.exemplo.com/recurso" value={currentStep.apiConfig?.url ?? ""} onChange={e => updateApiConfig(editingStep, { url: e.target.value })} disabled={!isDraft} />
              </div>
              <div className="field">
                <label>Metodo</label>
                <select className="select" value={currentStep.apiConfig?.method ?? (currentStep.type === 4 ? "POST" : "GET")} onChange={e => updateApiConfig(editingStep, { method: e.target.value })} disabled={!isDraft}>
                  {currentStep.type === 4 && <>
                    <option value="POST">POST</option>
                    <option value="PUT">PUT</option>
                  </>}
                  {currentStep.type !== 4 && <option value="GET">GET</option>}
                </select>
              </div>
              <div className="field">
                <label>Token</label>
                <select className="select" value={currentStep.apiConfig?.tokenName ?? ""} onChange={e => updateApiConfig(editingStep, { tokenName: e.target.value || undefined })} disabled={!isDraft}>
                  <option value="">Sem autenticacao</option>
                  {tokens.map((token, index) => <option key={`${token.id ?? "new"}-${index}`} value={token.name}>{token.name || `Token ${index + 1}`}</option>)}
                </select>
              </div>
              {currentStep.type === 5 &&
                <div className="field span2">
                  <label>Template da consulta</label>
                  <input className="input" placeholder="Ex.: ?id={{chaveAcesso}}" value={currentStep.apiConfig?.queryTemplate ?? ""} onChange={e => updateApiConfig(editingStep, { queryTemplate: e.target.value })} disabled={!isDraft} />
                </div>}
              <div className="field span2">
                <label className="toggle-line">
                  <input type="checkbox" checked={currentStep.apiConfig?.validateTls ?? true} onChange={e => updateApiConfig(editingStep, { validateTls: e.target.checked })} disabled={!isDraft} />
                  Validar certificado TLS/HTTPS
                </label>
              </div>
            </div>

            {(currentStep.type === 2 || currentStep.type === 5) && <div className="formgrid" style={{ marginTop: 16 }}>
              <ScheduleEditor config={currentStep.apiConfig} onChange={patch => updateApiConfig(editingStep, patch)} isDraft={isDraft} stepType={currentStep.type} />
            </div>}

            <AccordionSection
              title="Campos disponiveis para integracao"
              description="Reaproveite dados das etapas anteriores para montar URL, consulta ou identificar o registro enviado para a API."
              open={openSections.integrationFields}
              onToggle={() => toggleSection("integrationFields")}
            >
              {availableIntegrationFields.length === 0 && <div className="empty compact">Cadastre campos em etapas anteriores para reutiliza-los nesta integracao.</div>}

              {availableIntegrationFields.length > 0 && <div className="builder">
                {availableIntegrationFields.map(reference =>
                  <div className="field-block" key={`${reference.stepIndex}-${reference.key}`}>
                    <div className="builder-row" style={{ alignItems: "center", gap: 12, flexWrap: "wrap" }}>
                      <div style={{ minWidth: 220 }}>
                        <strong>{reference.label}</strong>
                        <div className="section-copy" style={{ marginTop: 4 }}>
                          Etapa {reference.stepIndex + 1} - {reference.stepName}
                        </div>
                      </div>
                      <code style={{ padding: "8px 10px", borderRadius: 10, background: "#f3f7f5", color: "#176b51", fontSize: 13 }}>
                        {reference.variable}
                      </code>
                      <button className="btn btn-ghost" type="button" onClick={() => copyReference(reference.variable)}>
                        <Copy size={15} />
                        {copiedReference === reference.variable ? "Copiado" : "Copiar"}
                      </button>
                      <button className="btn btn-ghost" type="button" onClick={() => insertReferenceIntoTestPayload(reference)}>
                        Inserir no teste
                      </button>
                      <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => insertIntoApiConfig("url", reference.variable)}>
                        Inserir na URL
                      </button>
                      {currentStep.type === 5 && <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => insertIntoApiConfig("queryTemplate", reference.variable)}>
                        Inserir na consulta
                      </button>}
                    </div>
                  </div>)}
              </div>}

              {currentStep.type === 4 && availableIntegrationFields.length > 0 && <div className="notice" style={{ marginTop: 14 }}>
                <strong>Campos enviados no body</strong>
                <div style={{ marginTop: 10, display: "flex", gap: 10, flexWrap: "wrap" }}>
                  <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={selectAllSendFields}>
                    Selecionar todos
                  </button>
                  <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={clearSendFields}>
                    Limpar selecao
                  </button>
                </div>
                <div style={{ marginTop: 10, display: "flex", flexWrap: "wrap", gap: 10 }}>
                  {availableIntegrationFields.map(reference =>
                    <label key={`payload-${reference.stepIndex}-${reference.key}`} className="toggle-line compact" style={{ padding: "8px 12px", border: "1px solid #d7e3dc", borderRadius: 999, background: "#fff" }}>
                      <input
                        type="checkbox"
                        checked={selectedSendFieldKeys.length === 0 ? true : selectedSendFieldKeys.includes(reference.key)}
                        onChange={() => toggleSendFieldKey(reference.key)}
                        disabled={!isDraft}
                      />
                      {reference.label}
                    </label>)}
                </div>
                <div className="section-copy" style={{ marginTop: 8 }}>
                  Se nenhum campo for marcado manualmente, o sistema envia todos os campos disponiveis ate esta etapa.
                </div>
                {selectedSendFieldKeys.length > 0 && <div style={{ marginTop: 14 }}>
                  <strong>Ordem do payload</strong>
                  <div className="builder" style={{ marginTop: 10 }}>
                    {orderedSelectedSendFields.map((reference, index) =>
                      <div className="field-block" key={`ordered-payload-${reference.key}`}>
                        <div className="builder-row" style={{ alignItems: "center", gap: 12, flexWrap: "wrap" }}>
                          <span className="step-chip">{index + 1}</span>
                          <div style={{ minWidth: 220 }}>
                            <strong>{reference.label}</strong>
                            <div className="section-copy" style={{ marginTop: 4 }}>{reference.variable}</div>
                          </div>
                          <button className="btn btn-ghost" type="button" disabled={!isDraft || index === 0} onClick={() => moveSendField(reference.key, "up")}>
                            <ArrowUp size={15} />
                            Subir
                          </button>
                          <button className="btn btn-ghost" type="button" disabled={!isDraft || index === orderedSelectedSendFields.length - 1} onClick={() => moveSendField(reference.key, "down")}>
                            <ArrowDown size={15} />
                            Descer
                          </button>
                        </div>
                      </div>)}
                  </div>
                </div>}
              </div>}

              {currentStep.type === 4 && availableIntegrationFields.length > 0 && <div className="notice" style={{ marginTop: 14 }}>
                <strong>API envio:</strong> esta etapa ja envia automaticamente no corpo JSON os dados capturados ate aqui, incluindo campos da etapa inicial como numero da nota fiscal.
                <pre style={{ whiteSpace: "pre-wrap", marginTop: 10 }}>{payloadPreview}</pre>
              </div>}

              {currentStep.type === 4 && <AccordionSection
                title="Body customizado"
                description='Opcionalmente, monte o corpo com nomes de propriedades diferentes dos campos internos. Ex.: numeroNota recebe {{notafiscal}}.'
                open={openSections.bodyMapping}
                onToggle={() => toggleSection("bodyMapping")}
                actions={<button className="btn btn-secondary" type="button" disabled={!isDraft} onClick={addBodyMapping}>
                  <Plus size={14} />
                  Adicionar mapeamento
                </button>}
              >
                <div style={{ display: "flex", gap: 10, flexWrap: "wrap", marginTop: 12 }}>
                  <button className="btn btn-ghost" type="button" disabled={!isDraft || availableIntegrationFields.length === 0} onClick={buildBodyMappingsFromSelectedFields}>
                    Gerar pelos campos selecionados
                  </button>
                </div>

                {currentBodyMappings.length === 0 && <div className="empty compact">Sem body customizado. Nesse caso, o sistema usa os campos selecionados acima.</div>}

                {currentBodyMappings.length > 0 && <div className="builder">
                  {currentBodyMappings.map((mapping, mappingIndex) =>
                    <div className="field-block" key={`body-mapping-${mappingIndex}`}>
                      <div className="builder-row" style={{ alignItems: "center", gap: 12, flexWrap: "wrap" }}>
                        <input
                          className="input"
                          style={{ minWidth: 200 }}
                          placeholder="nomePropriedade ou cliente.documento"
                          value={mapping.targetKey}
                          onChange={e => updateBodyMapping(mappingIndex, { targetKey: normalizeBodyTargetKey(e.target.value) })}
                          disabled={!isDraft}
                        />
                        <select
                          className="select"
                          style={{ minWidth: 260 }}
                          value={mapping.sourceReference}
                          onChange={e => updateBodyMapping(mappingIndex, { sourceReference: e.target.value })}
                          disabled={!isDraft}
                        >
                          <option value="">Selecione um campo</option>
                          {availableIntegrationFields.map(reference => <option key={`body-source-${reference.key}`} value={reference.variable}>{reference.label} - {reference.variable}</option>)}
                        </select>
                        <button className="btn btn-ghost" type="button" disabled={!isDraft || mappingIndex === 0} onClick={() => moveBodyMapping(mappingIndex, "up")}>
                          <ArrowUp size={15} />
                          Subir
                        </button>
                        <button className="btn btn-ghost" type="button" disabled={!isDraft || mappingIndex === currentBodyMappings.length - 1} onClick={() => moveBodyMapping(mappingIndex, "down")}>
                          <ArrowDown size={15} />
                          Descer
                        </button>
                        <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => duplicateBodyMapping(mappingIndex)}>
                          Duplicar
                        </button>
                        <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => removeBodyMapping(mappingIndex)}>
                          <Trash2 size={15} />
                          Remover
                        </button>
                      </div>
                    </div>)}
                </div>}

                {currentBodyMappings.length > 0 && <div className="notice" style={{ marginTop: 14 }}>
                  <strong>Preview do body customizado</strong>
                  <pre style={{ whiteSpace: "pre-wrap", marginTop: 10 }}>{customBodyPreview}</pre>
                  <div className="section-copy" style={{ marginTop: 8 }}>
                    Dica: use ponto no nome da propriedade para criar objetos aninhados, como <code>cliente.documento</code> ou <code>nota.numero</code>.
                  </div>
                </div>}
              </AccordionSection>}

              {currentStep.type === 5 && currentStep.fields.length > 0 && <AccordionSection
                title="Mapeamento da resposta da API"
                description="Defina qual propriedade do JSON retornado preenche cada campo desta etapa. Exemplo ViaCEP: logradouro, bairro, localidade, uf."
                open={openSections.responseMapping}
                onToggle={() => toggleSection("responseMapping")}
                actions={<button className="btn btn-secondary" type="button" disabled={!isDraft} onClick={fillResponseMappingsByFieldKey}>
                  Preencher pelo nome do campo
                </button>}
              >
                <div className="builder">
                  {currentStep.fields.map((field, fieldIndex) =>
                    <div className="field-block" key={`response-map-${field.id ?? "new"}-${fieldIndex}`}>
                      <div className="builder-row" style={{ alignItems: "center", gap: 12, flexWrap: "wrap" }}>
                        <div style={{ minWidth: 220 }}>
                          <strong>{field.label || `Campo ${fieldIndex + 1}`}</strong>
                          <div className="section-copy" style={{ marginTop: 4 }}>
                            Chave interna: {field.key || "defina a chave do campo"}
                          </div>
                        </div>
                        <input
                          className="input"
                          style={{ flex: 1, minWidth: 220 }}
                          placeholder="Ex.: logradouro ou data.endereco.uf"
                          value={field.key ? getResponseMappingValue(field.key) : ""}
                          onChange={e => field.key && updateResponseMapping(field.key, e.target.value)}
                          disabled={!isDraft || !field.key}
                        />
                        {field.key && <button className="btn btn-ghost" type="button" disabled={!isDraft} onClick={() => updateResponseMapping(field.key, field.key)}>
                          Usar mesma chave
                        </button>}
                      </div>
                    </div>)}
                </div>
              </AccordionSection>}
            </AccordionSection>

            <AccordionSection
              title="Teste controlado"
              description="Salve o rascunho e teste com um JSON de exemplo sem avancar execucoes reais."
              open={openSections.test}
              onToggle={() => toggleSection("test")}
              actions={<button className="btn btn-secondary" type="button" disabled={!flowId || !currentStep.id || testingStepId === currentStep.id} onClick={testIntegration}>
                <Send size={15} />
                {testingStepId === currentStep.id ? "Testando..." : "Testar integracao"}
              </button>}
            >
              <div className="field">
                <label>JSON de exemplo</label>
                <textarea className="textarea" value={testPayload} onChange={e => setTestPayload(e.target.value)} />
              </div>
              {testResult && <div className={testResult.success ? "notice" : "error"} style={{ marginTop: 12 }}>
                <strong>{testResult.success ? "Integracao concluida" : "Integracao falhou"}</strong>
                <div style={{ marginTop: 6 }}>Metodo: {testResult.method} | Status: {testResult.statusCode ?? "sem resposta"} | Tempo: {testResult.durationMs} ms</div>
                <div style={{ marginTop: 6, wordBreak: "break-word" }}>URL: {testResult.url}</div>
                {testResult.responsePreview && <pre style={{ whiteSpace: "pre-wrap", marginTop: 10 }}>{testResult.responsePreview}</pre>}
                {testResult.mappedFields && Object.keys(testResult.mappedFields).length > 0 && <div style={{ marginTop: 10 }}>
                  <strong>Campos mapeados</strong>
                  <pre style={{ whiteSpace: "pre-wrap", marginTop: 8 }}>{JSON.stringify(testResult.mappedFields, null, 2)}</pre>
                </div>}
                {testResult.errorMessage && <div style={{ marginTop: 8 }}>{testResult.errorMessage}</div>}
              </div>}
            </AccordionSection>
          </AccordionSection>}
        </div>}
      </div>

      <div className="actions">
        <button className="btn btn-secondary" type="button" onClick={() => router.back()}>Cancelar</button>
        {flowId && !isDraft && <button className="btn btn-secondary" type="button" disabled={creatingDraft} onClick={createDraftFromPublished}>
          <PencilLine size={16} />
          {creatingDraft ? "Gerando rascunho..." : "Criar rascunho"}
        </button>}
        {flowId && isDraft && <button className="btn btn-secondary" type="button" disabled={publishing} onClick={publishDraft}>
          <Send size={16} />
          {publishing ? "Publicando..." : "Publicar fluxo"}
        </button>}
        <button className="btn btn-primary" type="button" disabled={saving || !isDraft} onClick={saveFlow}>
          <Save size={16} />
          {saving ? "Salvando..." : flowId ? "Salvar alteracoes" : "Criar fluxo"}
        </button>
      </div>
    </section>
  </>;
}
